# Generated by Django 5.2.16 on 2026-07-21 20:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "name",
                    models.CharField(db_index=True, max_length=100, verbose_name="Nom"),
                ),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="Code"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Option",
                "verbose_name_plural": "Options",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SchoolLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "name",
                    models.CharField(db_index=True, max_length=100, verbose_name="Nom"),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Ordre"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Actif"
                    ),
                ),
            ],
            options={
                "verbose_name": "Niveau scolaire",
                "verbose_name_plural": "Niveaux scolaires",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SecretariatSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "key",
                    models.CharField(max_length=100, unique=True, verbose_name="Clé"),
                ),
                ("value", models.TextField(blank=True, verbose_name="Valeur")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Actif"
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètre du secrétariat",
                "verbose_name_plural": "Paramètres du secrétariat",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "name",
                    models.CharField(db_index=True, max_length=100, verbose_name="Nom"),
                ),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="Code"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Section",
                "verbose_name_plural": "Sections",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "label",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Libellé"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Date de début")),
                ("end_date", models.DateField(verbose_name="Date de fin")),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Active"
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Clôturée"
                    ),
                ),
            ],
            options={
                "verbose_name": "Année scolaire",
                "verbose_name_plural": "Années scolaires",
                "ordering": ["-start_date"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("start_date__lt", models.F("end_date"))),
                        name="secretariat_academic_year_dates_order",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Communication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Titre"
                    ),
                ),
                ("content", models.TextField(verbose_name="Contenu")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GENERALE", "Générale"),
                            ("ACADEMIQUE", "Académique"),
                            ("ADMINISTRATIVE", "Administrative"),
                            ("EVENEMENT", "Événement"),
                            ("URGENCE", "Urgence"),
                        ],
                        db_index=True,
                        default="GENERALE",
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("NORMALE", "Normale"),
                            ("IMPORTANTE", "Importante"),
                            ("URGENTE", "Urgente"),
                        ],
                        db_index=True,
                        default="NORMALE",
                        max_length=15,
                        verbose_name="Priorité",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("PROGRAMMEE", "Programmée"),
                            ("PUBLIEE", "Publiée"),
                            ("EXPIREE", "Expirée"),
                            ("ARCHIVEE", "Archivée"),
                        ],
                        db_index=True,
                        default="BROUILLON",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Publiée le"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expire le"
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        upload_to="communications/attachments/%Y/%m/",
                        verbose_name="Pièce jointe",
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Épinglée"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="communications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Communication",
                "verbose_name_plural": "Communications",
                "ordering": ["-is_pinned", "-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Guardian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "nom",
                    models.CharField(db_index=True, max_length=100, verbose_name="Nom"),
                ),
                (
                    "postnom",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="Postnom",
                    ),
                ),
                (
                    "prenom",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Prénom"
                    ),
                ),
                (
                    "sexe",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Masculin"), ("F", "Féminin"), ("O", "Autre")],
                        max_length=1,
                        verbose_name="Sexe",
                    ),
                ),
                (
                    "telephone_principal",
                    models.CharField(
                        db_index=True, max_length=30, verbose_name="Téléphone principal"
                    ),
                ),
                (
                    "telephone_secondaire",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Téléphone secondaire"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        db_index=True,
                        max_length=254,
                        verbose_name="Adresse e-mail",
                    ),
                ),
                ("adresse", models.TextField(blank=True, verbose_name="Adresse")),
                (
                    "profession",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Profession"
                    ),
                ),
                (
                    "numero_identification",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="Numéro d'identification",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Actif"
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Archivé"
                    ),
                ),
            ],
            options={
                "verbose_name": "Responsable",
                "verbose_name_plural": "Responsables",
                "ordering": ["nom", "postnom", "prenom"],
                "indexes": [
                    models.Index(
                        fields=["nom", "postnom", "prenom"],
                        name="secretariat_nom_193219_idx",
                    ),
                    models.Index(
                        fields=["is_active", "is_archived"],
                        name="secretariat_is_acti_0f12c1_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SchoolClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "name",
                    models.CharField(db_index=True, max_length=100, verbose_name="Nom"),
                ),
                (
                    "code",
                    models.CharField(db_index=True, max_length=30, verbose_name="Code"),
                ),
                (
                    "max_capacity",
                    models.PositiveIntegerField(verbose_name="Capacité maximale"),
                ),
                (
                    "room",
                    models.CharField(blank=True, max_length=100, verbose_name="Local"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="school_classes",
                        to="secretariat.academicyear",
                        verbose_name="Année scolaire",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="school_classes",
                        to="secretariat.option",
                        verbose_name="Option",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="school_classes",
                        to="secretariat.schoollevel",
                        verbose_name="Niveau",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="school_classes",
                        to="secretariat.section",
                        verbose_name="Section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Classe",
                "verbose_name_plural": "Classes",
                "ordering": ["academic_year", "level__order", "name"],
            },
        ),
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "name",
                    models.CharField(db_index=True, max_length=150, verbose_name="Nom"),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Code"),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Obligatoire"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Actif"
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_types",
                        to="secretariat.schoollevel",
                        verbose_name="Niveau",
                    ),
                ),
            ],
            options={
                "verbose_name": "Type de document",
                "verbose_name_plural": "Types de documents",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="option",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="options",
                to="secretariat.section",
                verbose_name="Section",
            ),
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "matricule",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Matricule"
                    ),
                ),
                (
                    "nom",
                    models.CharField(db_index=True, max_length=100, verbose_name="Nom"),
                ),
                (
                    "postnom",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="Postnom",
                    ),
                ),
                (
                    "prenom",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Prénom"
                    ),
                ),
                (
                    "sexe",
                    models.CharField(
                        choices=[("M", "Masculin"), ("F", "Féminin"), ("O", "Autre")],
                        max_length=1,
                        verbose_name="Sexe",
                    ),
                ),
                ("date_naissance", models.DateField(verbose_name="Date de naissance")),
                (
                    "lieu_naissance",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Lieu de naissance"
                    ),
                ),
                (
                    "nationalite",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nationalité"
                    ),
                ),
                ("adresse", models.TextField(blank=True, verbose_name="Adresse")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        upload_to="students/photos/%Y/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "ancien_etablissement",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Ancien établissement"
                    ),
                ),
                ("date_admission", models.DateField(verbose_name="Date d'admission")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ACTIF", "Actif"),
                            ("TRANSFERE", "Transféré"),
                            ("ABANDON", "Abandon"),
                            ("DIPLOME", "Diplômé"),
                            ("SUSPENDU", "Suspendu"),
                            ("ARCHIVE", "Archivé"),
                        ],
                        db_index=True,
                        default="ACTIF",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Actif"
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Archivé"
                    ),
                ),
                (
                    "groupe_sanguin",
                    models.CharField(
                        blank=True, max_length=5, verbose_name="Groupe sanguin"
                    ),
                ),
                ("allergies", models.TextField(blank=True, verbose_name="Allergies")),
                (
                    "conditions_medicales",
                    models.TextField(blank=True, verbose_name="Conditions médicales"),
                ),
                (
                    "observations",
                    models.TextField(blank=True, verbose_name="Observations"),
                ),
            ],
            options={
                "verbose_name": "Élève",
                "verbose_name_plural": "Élèves",
                "ordering": ["nom", "postnom", "prenom"],
                "indexes": [
                    models.Index(
                        fields=["nom", "postnom", "prenom"],
                        name="secretariat_nom_803a4f_idx",
                    ),
                    models.Index(
                        fields=["statut", "is_active", "is_archived"],
                        name="secretariat_statut_30dbfc_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "enrollment_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Numéro d'inscription"
                    ),
                ),
                (
                    "enrollment_type",
                    models.CharField(
                        choices=[
                            ("NOUVELLE_INSCRIPTION", "Nouvelle inscription"),
                            ("REINSCRIPTION", "Réinscription"),
                            ("TRANSFERT_ENTRANT", "Transfert entrant"),
                        ],
                        max_length=30,
                        verbose_name="Type d'inscription",
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateField(verbose_name="Date d'inscription"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("VALIDEE", "Validée"),
                            ("ANNULEE", "Annulée"),
                            ("CLOTUREE", "Clôturée"),
                        ],
                        db_index=True,
                        default="BROUILLON",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "provenance",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Provenance"
                    ),
                ),
                (
                    "observation",
                    models.TextField(blank=True, verbose_name="Observation"),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="secretariat.academicyear",
                        verbose_name="Année scolaire",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_enrollments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créée par",
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="secretariat.schoolclass",
                        verbose_name="Classe",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="secretariat.student",
                        verbose_name="Élève",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription",
                "verbose_name_plural": "Inscriptions",
                "ordering": ["-enrollment_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommunicationTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("ALL_PARENTS", "Tous les parents"),
                            ("ACADEMIC_YEAR", "Année scolaire"),
                            ("LEVEL", "Niveau"),
                            ("SECTION", "Section"),
                            ("OPTION", "Option"),
                            ("CLASS", "Classe"),
                            ("STUDENT", "Élève"),
                            ("GUARDIAN", "Responsable"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Type de cible",
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communication_targets",
                        to="secretariat.academicyear",
                        verbose_name="Année scolaire",
                    ),
                ),
                (
                    "communication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="secretariat.communication",
                        verbose_name="Communication",
                    ),
                ),
                (
                    "guardian",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communication_targets",
                        to="secretariat.guardian",
                        verbose_name="Responsable",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communication_targets",
                        to="secretariat.option",
                        verbose_name="Option",
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communication_targets",
                        to="secretariat.schoolclass",
                        verbose_name="Classe",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communication_targets",
                        to="secretariat.schoollevel",
                        verbose_name="Niveau",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communication_targets",
                        to="secretariat.section",
                        verbose_name="Section",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communication_targets",
                        to="secretariat.student",
                        verbose_name="Élève",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cible de communication",
                "verbose_name_plural": "Cibles de communication",
                "ordering": ["communication", "target_type"],
            },
        ),
        migrations.CreateModel(
            name="CommunicationReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Lu le"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "communication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="secretariat.communication",
                        verbose_name="Communication",
                    ),
                ),
                (
                    "guardian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communication_receipts",
                        to="secretariat.guardian",
                        verbose_name="Responsable",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communication_receipts",
                        to="secretariat.student",
                        verbose_name="Élève",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accusé de communication",
                "verbose_name_plural": "Accusés de communication",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClassTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("motif", models.TextField(verbose_name="Motif")),
                (
                    "transfer_date",
                    models.DateField(db_index=True, verbose_name="Date du transfert"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_class_transfers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Effectué par",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="class_transfers",
                        to="secretariat.enrollment",
                        verbose_name="Inscription",
                    ),
                ),
                (
                    "from_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_transfers",
                        to="secretariat.schoolclass",
                        verbose_name="Classe d'origine",
                    ),
                ),
                (
                    "to_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_transfers",
                        to="secretariat.schoolclass",
                        verbose_name="Classe de destination",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="class_transfers",
                        to="secretariat.student",
                        verbose_name="Élève",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transfert de classe",
                "verbose_name_plural": "Transferts de classe",
                "ordering": ["-transfer_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "qr_identifier",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Identifiant QR"
                    ),
                ),
                (
                    "card_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Numéro de carte"
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Générée le"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expire le"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "is_blocked",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Bloquée"
                    ),
                ),
                (
                    "block_reason",
                    models.TextField(blank=True, verbose_name="Motif du blocage"),
                ),
                (
                    "qr_image",
                    models.ImageField(
                        blank=True,
                        upload_to="students/cards/qr/%Y/",
                        verbose_name="Image du code QR",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        upload_to="students/cards/pdf/%Y/",
                        verbose_name="Carte PDF",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifiée le"),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cards",
                        to="secretariat.enrollment",
                        verbose_name="Inscription",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_student_cards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Générée par",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cards",
                        to="secretariat.student",
                        verbose_name="Élève",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carte d'élève",
                "verbose_name_plural": "Cartes d'élèves",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="students/documents/%Y/%m/", verbose_name="Fichier"
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("VALIDATED", "Validé"),
                            ("REJECTED", "Rejeté"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                        verbose_name="Statut de vérification",
                    ),
                ),
                ("received_at", models.DateTimeField(verbose_name="Reçu le")),
                (
                    "observation",
                    models.TextField(blank=True, verbose_name="Observation"),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_documents",
                        to="secretariat.documenttype",
                        verbose_name="Type de document",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="secretariat.student",
                        verbose_name="Élève",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_student_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vérifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document d'élève",
                "verbose_name_plural": "Documents d'élèves",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentGuardian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lien_parente",
                    models.CharField(
                        choices=[
                            ("PERE", "Père"),
                            ("MERE", "Mère"),
                            ("TUTEUR", "Tuteur légal"),
                            ("FRERE", "Frère"),
                            ("SOEUR", "Sœur"),
                            ("ONCLE", "Oncle"),
                            ("TANTE", "Tante"),
                            ("GRAND_PARENT", "Grand-parent"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Lien de parenté",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, verbose_name="Responsable principal"
                    ),
                ),
                (
                    "is_emergency_contact",
                    models.BooleanField(
                        default=False, verbose_name="Contact d'urgence"
                    ),
                ),
                (
                    "can_pickup",
                    models.BooleanField(
                        default=True, verbose_name="Autorisé à récupérer l'élève"
                    ),
                ),
                (
                    "receives_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Reçoit les notifications"
                    ),
                ),
                (
                    "lives_with_student",
                    models.BooleanField(default=False, verbose_name="Vit avec l'élève"),
                ),
                (
                    "observation",
                    models.TextField(blank=True, verbose_name="Observation"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "guardian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_links",
                        to="secretariat.guardian",
                        verbose_name="Responsable",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardian_links",
                        to="secretariat.student",
                        verbose_name="Élève",
                    ),
                ),
            ],
            options={
                "verbose_name": "Responsable d'élève",
                "verbose_name_plural": "Responsables d'élèves",
                "ordering": ["student", "-is_primary", "guardian"],
            },
        ),
        migrations.AddIndex(
            model_name="communication",
            index=models.Index(
                fields=["status", "published_at"], name="secretariat_status_d1695a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communication",
            index=models.Index(
                fields=["category", "priority"], name="secretariat_categor_696896_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schoolclass",
            index=models.Index(
                fields=["academic_year", "is_active"],
                name="secretariat_academi_136017_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="schoolclass",
            index=models.Index(
                fields=["level", "section", "option"],
                name="secretariat_level_i_ceac18_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="schoolclass",
            constraint=models.UniqueConstraint(
                fields=("code", "academic_year"),
                name="secretariat_unique_class_code_per_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="schoolclass",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_capacity__gt", 0)),
                name="secretariat_school_class_positive_capacity",
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["academic_year", "status"],
                name="secretariat_academi_dca6ae_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["school_class", "status"], name="secretariat_school__2cd408_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["student", "status"], name="secretariat_student_c5f7bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communicationtarget",
            index=models.Index(
                fields=["communication", "target_type"],
                name="secretariat_communi_524b20_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="communicationreceipt",
            index=models.Index(
                fields=["guardian", "read_at"], name="secretariat_guardia_c5ec38_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communicationreceipt",
            index=models.Index(
                fields=["communication", "guardian"],
                name="secretariat_communi_304e3a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="classtransfer",
            index=models.Index(
                fields=["student", "transfer_date"],
                name="secretariat_student_fbf6d1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="classtransfer",
            index=models.Index(
                fields=["enrollment", "transfer_date"],
                name="secretariat_enrollm_8f0c95_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentcard",
            index=models.Index(
                fields=["student", "is_active", "is_blocked"],
                name="secretariat_student_dbbf90_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentcard",
            index=models.Index(
                fields=["enrollment", "is_active"],
                name="secretariat_enrollm_70f02b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentdocument",
            index=models.Index(
                fields=["student", "verification_status"],
                name="secretariat_student_b31e6c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentdocument",
            index=models.Index(
                fields=["document_type", "verification_status"],
                name="secretariat_documen_dff0ae_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentguardian",
            index=models.Index(
                fields=["student", "is_primary"], name="secretariat_student_663de5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentguardian",
            index=models.Index(
                fields=["guardian", "receives_notifications"],
                name="secretariat_guardia_9f054a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentguardian",
            constraint=models.UniqueConstraint(
                fields=("student", "guardian"),
                name="secretariat_unique_student_guardian",
            ),
        ),
    ]
