# Generated by Django 5.2.16 on 2026-07-22 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _column_names(schema_editor, table):
    with schema_editor.connection.cursor() as cursor:
        description = schema_editor.connection.introspection.get_table_description(
            cursor, table
        )
    return {col.name for col in description}


def apply_pin_fields(apps, schema_editor):
    """Add pin columns in a vendor-safe way (MySQL MyISAM-compatible, SQLite tests)."""
    table = "secretariat_communication"
    existing = _column_names(schema_editor, table)
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if "pinned_at" not in existing:
            if vendor == "sqlite":
                cursor.execute(f"ALTER TABLE {table} ADD COLUMN pinned_at datetime NULL")
            else:
                cursor.execute(f"ALTER TABLE {table} ADD COLUMN pinned_at datetime(6) NULL")
        if "pinned_by_id" not in existing:
            # No DB FK: accounts_user may be MyISAM while this table is InnoDB.
            coltype = "INTEGER" if vendor == "sqlite" else "BIGINT"
            cursor.execute(f"ALTER TABLE {table} ADD COLUMN pinned_by_id {coltype} NULL")

        if vendor == "sqlite":
            cursor.execute(
                f"CREATE INDEX IF NOT EXISTS secretariat_is_pinn_bcfe5c_idx "
                f"ON {table} (is_pinned, pinned_at)"
            )
            return

        cursor.execute(
            f"SHOW INDEX FROM {table} WHERE Key_name = %s",
            ["secretariat_is_pinn_bcfe5c_idx"],
        )
        if not cursor.fetchall():
            cursor.execute(
                f"CREATE INDEX secretariat_is_pinn_bcfe5c_idx "
                f"ON {table} (is_pinned, pinned_at)"
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("secretariat", "0001_initial_secretariat"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(apply_pin_fields, noop_reverse),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="communication",
                    name="pinned_at",
                    field=models.DateTimeField(
                        blank=True, null=True, verbose_name="Épinglée le"
                    ),
                ),
                migrations.AddField(
                    model_name="communication",
                    name="pinned_by",
                    field=models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pinned_communications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Épinglée par",
                    ),
                ),
                migrations.AddIndex(
                    model_name="communication",
                    index=models.Index(
                        fields=["is_pinned", "pinned_at"],
                        name="secretariat_is_pinn_bcfe5c_idx",
                    ),
                ),
            ],
        ),
    ]
