# Generated by Django 5.2.16 on 2026-07-23 20:27

from django.db import migrations, models


def backfill_class_letters(apps, schema_editor):
    SchoolClass = apps.get_model("secretariat", "SchoolClass")
    allowed = set("ABCDEFGH")
    to_update = []
    for school_class in SchoolClass.objects.all().only("id", "code", "name", "letter"):
        letter = ""
        code = (school_class.code or "").strip()
        if "-" in code:
            suffix = code.rsplit("-", 1)[-1].upper()
            if len(suffix) == 1 and suffix in allowed:
                letter = suffix
        if not letter:
            name = (school_class.name or "").strip()
            if name:
                last = name.split()[-1].upper()
                if len(last) == 1 and last in allowed:
                    letter = last
        if letter and school_class.letter != letter:
            school_class.letter = letter
            to_update.append(school_class)
    if to_update:
        SchoolClass.objects.bulk_update(to_update, ["letter"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("secretariat", "0003_academic_year_closure_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolclass",
            name="letter",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                    ("F", "F"),
                    ("G", "G"),
                    ("H", "H"),
                ],
                db_index=True,
                help_text="Lettre de la classe (A, B, C, D…).",
                max_length=1,
                verbose_name="Lettre",
            ),
        ),
        migrations.RunPython(backfill_class_letters, noop_reverse),
        migrations.AddIndex(
            model_name="schoolclass",
            index=models.Index(
                fields=["academic_year", "level", "letter"],
                name="secretariat_academi_e47c8e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="schoolclass",
            constraint=models.UniqueConstraint(
                fields=("name", "academic_year"),
                name="secretariat_unique_class_name_per_year",
                violation_error_message=(
                    "Une classe avec ce nom existe déjà pour cette année scolaire."
                ),
            ),
        ),
        migrations.AlterConstraint(
            model_name="schoolclass",
            name="secretariat_unique_class_code_per_year",
            constraint=models.UniqueConstraint(
                fields=("code", "academic_year"),
                name="secretariat_unique_class_code_per_year",
                violation_error_message=(
                    "Une classe avec ce code existe déjà pour cette année scolaire."
                ),
            ),
        ),
    ]
