# Generated by Django 5.2.16 on 2026-07-20 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("user_created", "Création d'utilisateur"),
                            ("user_updated", "Modification d'utilisateur"),
                            ("role_changed", "Changement de rôle"),
                            ("user_activated", "Activation"),
                            ("user_deactivated", "Désactivation"),
                            ("user_archived", "Archivage"),
                            ("password_reset", "Réinitialisation du mot de passe"),
                            ("login_success", "Connexion réussie"),
                            ("login_failed", "Connexion échouée"),
                            ("profile_updated", "Modification du profil"),
                            ("password_changed", "Changement de mot de passe"),
                            ("logout", "Déconnexion"),
                            ("setup_completed", "Configuration initiale"),
                            ("permission_toggled", "Modification de permission"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("entity_type", models.CharField(blank=True, max_length=100)),
                ("entity_public_id", models.CharField(blank=True, max_length=64)),
                ("description", models.TextField()),
                ("old_values", models.JSONField(blank=True, default=dict)),
                ("new_values", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal d'activité",
                "verbose_name_plural": "Journal d'activités",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempted_username", models.CharField(max_length=150)),
                ("success", models.BooleanField(default=False)),
                ("failure_reason", models.CharField(blank=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("device", models.CharField(blank=True, max_length=100)),
                ("browser", models.CharField(blank=True, max_length=100)),
                ("operating_system", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="login_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tentative de connexion",
                "verbose_name_plural": "Tentatives de connexion",
                "ordering": ["-created_at"],
            },
        ),
    ]
