# Generated by Django 5.2.16 on 2026-07-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("user_created", "Création d'utilisateur"),
                    ("user_updated", "Modification d'utilisateur"),
                    ("role_changed", "Changement de rôle"),
                    ("user_activated", "Activation"),
                    ("user_deactivated", "Désactivation"),
                    ("user_archived", "Archivage"),
                    ("password_reset", "Réinitialisation du mot de passe"),
                    ("login_success", "Connexion réussie"),
                    ("login_failed", "Connexion échouée"),
                    ("profile_updated", "Modification du profil"),
                    ("password_changed", "Changement de mot de passe"),
                    ("logout", "Déconnexion"),
                    ("setup_completed", "Configuration initiale"),
                    ("permission_toggled", "Modification de permission"),
                    ("academic_created", "Création académique"),
                    ("academic_updated", "Modification académique"),
                    ("academic_activated", "Activation d'année scolaire"),
                    ("academic_closed", "Clôture d'année scolaire"),
                    ("student_created", "Création d'élève"),
                    ("student_updated", "Modification d'élève"),
                    ("student_archived", "Archivage d'élève"),
                    ("guardian_created", "Création de responsable"),
                    ("guardian_updated", "Modification de responsable"),
                    ("guardian_associated", "Association de responsable"),
                    ("enrollment_created", "Création d'inscription"),
                    ("student_reenrolled", "Réinscription d'élève"),
                    ("class_transferred", "Transfert de classe"),
                    ("document_uploaded", "Dépôt de document"),
                    ("document_verified", "Vérification de document"),
                    ("card_generated", "Génération de carte"),
                    ("card_blocked", "Blocage de carte"),
                    ("card_replaced", "Remplacement de carte"),
                    ("communication_drafted", "Brouillon de communication"),
                    ("communication_published", "Publication de communication"),
                    ("communication_scheduled", "Programmation de communication"),
                    ("communication_archived", "Archivage de communication"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
