# Generated by Django 5.2.16 on 2026-07-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_secretariat_audit_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user_created', "Création d'utilisateur"), ('user_updated', "Modification d'utilisateur"), ('role_changed', 'Changement de rôle'), ('user_activated', 'Activation'), ('user_deactivated', 'Désactivation'), ('user_archived', 'Archivage'), ('password_reset', 'Réinitialisation du mot de passe'), ('login_success', 'Connexion réussie'), ('login_failed', 'Connexion échouée'), ('profile_updated', 'Modification du profil'), ('password_changed', 'Changement de mot de passe'), ('logout', 'Déconnexion'), ('setup_completed', 'Configuration initiale'), ('permission_toggled', 'Modification de permission'), ('academic_created', 'Création académique'), ('academic_updated', 'Modification académique'), ('academic_activated', "Activation d'année scolaire"), ('academic_closed', "Clôture d'année scolaire"), ('student_created', "Création d'élève"), ('student_updated', "Modification d'élève"), ('student_archived', "Archivage d'élève"), ('guardian_created', 'Création de responsable'), ('guardian_updated', 'Modification de responsable'), ('guardian_associated', 'Association de responsable'), ('enrollment_created', "Création d'inscription"), ('student_reenrolled', "Réinscription d'élève"), ('class_transferred', 'Transfert de classe'), ('document_uploaded', 'Dépôt de document'), ('document_verified', 'Vérification de document'), ('card_generated', 'Génération de carte'), ('card_blocked', 'Blocage de carte'), ('card_replaced', 'Remplacement de carte'), ('communication_drafted', 'Brouillon de communication'), ('communication_published', 'Publication de communication'), ('communication_scheduled', 'Programmation de communication'), ('communication_archived', 'Archivage de communication'), ('academic_year_selected', "Sélection d'année scolaire"), ('communication_pinned', 'Épinglage de communication'), ('communication_unpinned', 'Désépinglage de communication'), ('entity_deleted', 'Suppression définitive'), ('entity_restored', 'Restauration'), ('entity_deactivated', 'Désactivation'), ('entity_reactivated', 'Réactivation'), ('fee_created', 'Création de frais'), ('fee_updated', 'Modification de frais'), ('fee_submitted', 'Soumission de frais'), ('fee_approved', 'Approbation de frais'), ('fee_rejected', 'Rejet de frais'), ('fee_archived', 'Archivage de frais'), ('fee_withdrawn', 'Retrait de demande de frais'), ('payment_recorded', 'Enregistrement de paiement'), ('payment_cancelled', 'Annulation de paiement'), ('receipt_generated', 'Génération de reçu'), ('finance_exported', 'Export comptable')], db_index=True, max_length=50),
        ),
    ]
