# Generated by Django 5.2.16 on 2026-07-27 15:59

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secretariat', '0004_school_class_letter_and_unique_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Catégorie de frais',
                'verbose_name_plural': 'Catégories de frais',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('receipt_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de reçu')),
                ('payment_date', models.DateField(db_index=True, verbose_name='Date de paiement')),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant total')),
                ('currency', models.CharField(default='CDF', max_length=10, verbose_name='Devise')),
                ('payment_method', models.CharField(choices=[('ESPECES', 'Espèces'), ('MOBILE_MONEY', 'Mobile money'), ('VIREMENT', 'Virement'), ('DEPOT', 'Dépôt'), ('CARTE', 'Carte'), ('AUTRE', 'Autre')], default='ESPECES', max_length=20, verbose_name='Mode de paiement')),
                ('transaction_reference', models.CharField(blank=True, max_length=100, verbose_name='Référence de transaction')),
                ('payer_name', models.CharField(blank=True, max_length=200, verbose_name='Nom du payeur')),
                ('payer_phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone du payeur')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('status', models.CharField(choices=[('VALIDE', 'Validé'), ('ANNULE', 'Annulé')], db_index=True, default='VALIDE', max_length=15, verbose_name='Statut')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Annulé le')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name="Motif d'annulation")),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='secretariat.academicyear', verbose_name='Année scolaire')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_payments', to=settings.AUTH_USER_MODEL, verbose_name='Annulé par')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='secretariat.enrollment', verbose_name='Inscription')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='secretariat.student', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('last_value', models.PositiveIntegerField(default=0, verbose_name='Dernière valeur')),
                ('academic_year', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_sequence', to='secretariat.academicyear', verbose_name='Année scolaire')),
            ],
            options={
                'verbose_name': 'Séquence de reçu',
                'verbose_name_plural': 'Séquences de reçus',
            },
        ),
        migrations.CreateModel(
            name='SchoolFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('code', models.CharField(db_index=True, max_length=30, verbose_name='Code')),
                ('label', models.CharField(max_length=200, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('currency', models.CharField(default='CDF', max_length=10, verbose_name='Devise')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Obligatoire')),
                ('allow_partial', models.BooleanField(default=True, verbose_name='Paiement partiel autorisé')),
                ('application_type', models.CharField(choices=[('TOUTES_LES_CLASSES', 'Toutes les classes'), ('CLASSES_SELECTIONNEES', 'Classes sélectionnées'), ('NIVEAU', 'Niveau'), ('SECTION', 'Section'), ('OPTION', 'Option')], default='TOUTES_LES_CLASSES', max_length=30, verbose_name="Type d'application")),
                ('status', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE', 'En attente'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté'), ('ANNULE', 'Annulé'), ('ARCHIVE', 'Archivé')], db_index=True, default='BROUILLON', max_length=15, verbose_name='Statut')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Soumis le')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Revu le')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motif de rejet')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('is_archived', models.BooleanField(db_index=True, default=False, verbose_name='Archivé')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_fees', to='secretariat.academicyear', verbose_name='Année scolaire')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fees', to='finance.feecategory', verbose_name='Catégorie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_school_fees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_school_fees', to=settings.AUTH_USER_MODEL, verbose_name='Revue par')),
            ],
            options={
                'verbose_name': 'Frais scolaire',
                'verbose_name_plural': 'Frais scolaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_targets', to='secretariat.schoollevel', verbose_name='Niveau')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_targets', to='secretariat.option', verbose_name='Option')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_targets', to='secretariat.schoolclass', verbose_name='Classe')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_targets', to='secretariat.section', verbose_name='Section')),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='finance.schoolfee', verbose_name='Frais')),
            ],
            options={
                'verbose_name': 'Cible de frais',
                'verbose_name_plural': 'Cibles de frais',
                'ordering': ['fee', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FeeApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('action', models.CharField(choices=[('CREATED', 'Création'), ('UPDATED', 'Modification'), ('SUBMITTED', 'Soumission'), ('WITHDRAWN', 'Retrait'), ('APPROVED', 'Approbation'), ('REJECTED', 'Rejet'), ('ARCHIVED', 'Archivage'), ('CANCELLED', 'Annulation')], max_length=20, verbose_name='Action')),
                ('previous_status', models.CharField(blank=True, max_length=15, verbose_name='Statut précédent')),
                ('new_status', models.CharField(blank=True, max_length=15, verbose_name='Nouveau statut')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_approval_actions', to=settings.AUTH_USER_MODEL, verbose_name='Acteur')),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to='finance.schoolfee', verbose_name='Frais')),
            ],
            options={
                'verbose_name': "Historique d'approbation",
                'verbose_name_plural': "Historiques d'approbation",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentFeeObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant dû')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant payé')),
                ('status', models.CharField(choices=[('NON_PAYE', 'Non payé'), ('PARTIEL', 'Partiel'), ('PAYE', 'Payé'), ('EXONERE', 'Exonéré'), ('ANNULE', 'Annulé')], db_index=True, default='NON_PAYE', max_length=15, verbose_name='Statut')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_obligations', to='secretariat.enrollment', verbose_name='Inscription')),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligations', to='finance.schoolfee', verbose_name='Frais')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_obligations', to='secretariat.student', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Obligation de frais',
                'verbose_name_plural': 'Obligations de frais',
                'ordering': ['fee__label', 'enrollment_id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.payment', verbose_name='Paiement')),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.studentfeeobligation', verbose_name='Obligation')),
            ],
            options={
                'verbose_name': 'Allocation de paiement',
                'verbose_name_plural': 'Allocations de paiement',
                'ordering': ['payment_id', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['academic_year', 'status'], name='finance_pay_academi_3891b6_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['enrollment', 'status'], name='finance_pay_enrollm_ba2ceb_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['student', 'payment_date'], name='finance_pay_student_809d60_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date', 'status'], name='finance_pay_payment_a192f5_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolfee',
            index=models.Index(fields=['academic_year', 'status'], name='finance_sch_academi_b3f84b_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolfee',
            index=models.Index(fields=['academic_year', 'is_active', 'is_archived'], name='finance_sch_academi_d53255_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolfee',
            index=models.Index(fields=['category', 'status'], name='finance_sch_categor_204a38_idx'),
        ),
        migrations.AddConstraint(
            model_name='schoolfee',
            constraint=models.UniqueConstraint(fields=('code', 'academic_year'), name='finance_unique_fee_code_per_year', violation_error_message='Un frais avec ce code existe déjà pour cette année scolaire.'),
        ),
        migrations.AddIndex(
            model_name='feetarget',
            index=models.Index(fields=['fee', 'school_class'], name='finance_fee_fee_id_7766c2_idx'),
        ),
        migrations.AddIndex(
            model_name='feetarget',
            index=models.Index(fields=['fee', 'level'], name='finance_fee_fee_id_b60e60_idx'),
        ),
        migrations.AddIndex(
            model_name='feetarget',
            index=models.Index(fields=['fee', 'section'], name='finance_fee_fee_id_0eabc9_idx'),
        ),
        migrations.AddIndex(
            model_name='feetarget',
            index=models.Index(fields=['fee', 'option'], name='finance_fee_fee_id_f95ec3_idx'),
        ),
        migrations.AddIndex(
            model_name='feeapprovalhistory',
            index=models.Index(fields=['fee', 'created_at'], name='finance_fee_fee_id_903df2_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfeeobligation',
            index=models.Index(fields=['enrollment', 'status'], name='finance_stu_enrollm_70b1ca_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfeeobligation',
            index=models.Index(fields=['student', 'status'], name='finance_stu_student_f94e3a_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfeeobligation',
            index=models.Index(fields=['fee', 'status'], name='finance_stu_fee_id_038532_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentfeeobligation',
            constraint=models.UniqueConstraint(fields=('fee', 'enrollment'), name='finance_unique_obligation_fee_enrollment', violation_error_message='Une obligation existe déjà pour ce frais et cette inscription.'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['obligation', 'payment'], name='finance_pay_obligat_b43246_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.UniqueConstraint(fields=('payment', 'obligation'), name='finance_unique_allocation_payment_obligation'),
        ),
    ]
