# Generated by Django 5.2.16 on 2026-07-27 19:17

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_schoolfee_schedule_group'),
        ('secretariat', '0004_school_class_letter_and_unique_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeAmountChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('new_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Nouveau montant')),
                ('previous_base_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant de base précédent')),
                ('scope', models.CharField(choices=[('CETTE_CLASSE', 'Cette classe uniquement'), ('CLASSES_SELECTIONNEES', 'Classes spécifiques'), ('TOUTES_LES_CLASSES', 'Toutes les classes')], default='CETTE_CLASSE', max_length=30, verbose_name='Portée')),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté'), ('ANNULE', 'Annulé')], db_index=True, default='EN_ATTENTE', max_length=15, verbose_name='Statut')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motif de rejet')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Soumis le')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Revu le')),
            ],
            options={
                'verbose_name': 'Demande de modification de montant',
                'verbose_name_plural': 'Demandes de modification de montant',
                'ordering': ['-submitted_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeClassAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
            ],
            options={
                'verbose_name': 'Montant de frais par classe',
                'verbose_name_plural': 'Montants de frais par classe',
                'ordering': ['fee', 'school_class__name'],
            },
        ),
        migrations.RenameIndex(
            model_name='feerevisionrequest',
            new_name='finance_fee_fee_id_08b4d8_idx',
            old_name='finance_fee_fee_id_7f2a1a_idx',
        ),
        migrations.RenameIndex(
            model_name='feerevisionrequest',
            new_name='finance_fee_status_ef58f1_idx',
            old_name='finance_fee_status_9c4b2d_idx',
        ),
        migrations.AddField(
            model_name='feeamountchangerequest',
            name='fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount_change_requests', to='finance.schoolfee', verbose_name='Frais'),
        ),
        migrations.AddField(
            model_name='feeamountchangerequest',
            name='origin_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='originated_fee_amount_changes', to='secretariat.schoolclass', verbose_name="Classe d'origine"),
        ),
        migrations.AddField(
            model_name='feeamountchangerequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_amount_change_requests', to=settings.AUTH_USER_MODEL, verbose_name='Demandé par'),
        ),
        migrations.AddField(
            model_name='feeamountchangerequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_fee_amount_changes', to=settings.AUTH_USER_MODEL, verbose_name='Revu par'),
        ),
        migrations.AddField(
            model_name='feeamountchangerequest',
            name='target_classes',
            field=models.ManyToManyField(blank=True, related_name='fee_amount_change_requests', to='secretariat.schoolclass', verbose_name='Classes cibles'),
        ),
        migrations.AddField(
            model_name='feeclassamount',
            name='fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_amounts', to='finance.schoolfee', verbose_name='Frais'),
        ),
        migrations.AddField(
            model_name='feeclassamount',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_amounts', to='secretariat.schoolclass', verbose_name='Classe'),
        ),
        migrations.AddIndex(
            model_name='feeamountchangerequest',
            index=models.Index(fields=['status', 'submitted_at'], name='finance_fee_status_912c1c_idx'),
        ),
        migrations.AddIndex(
            model_name='feeamountchangerequest',
            index=models.Index(fields=['fee', 'status'], name='finance_fee_fee_id_b60393_idx'),
        ),
        migrations.AddIndex(
            model_name='feeclassamount',
            index=models.Index(fields=['fee', 'school_class'], name='finance_fee_fee_id_abfdd8_idx'),
        ),
        migrations.AddConstraint(
            model_name='feeclassamount',
            constraint=models.UniqueConstraint(fields=('fee', 'school_class'), name='finance_feeclassamount_fee_class_uniq'),
        ),
    ]
