# Generated by Django 5.2.16 on 2026-07-30 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_seed_prefet_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['nom', 'prenom'], 'permissions': [('view_admin_dashboard', 'Peut consulter le tableau de bord administrateur'), ('manage_users', 'Peut gérer les utilisateurs'), ('view_login_history', "Peut consulter l'historique des connexions"), ('view_audit_log', "Peut consulter le journal d'activités"), ('manage_own_profile', 'Peut gérer son propre profil'), ('view_bi_dashboard', 'Peut consulter le tableau de bord décisionnel BI'), ('view_enrollment_analytics', "Peut consulter l'analyse des effectifs"), ('view_financial_analytics', "Peut consulter l'analyse financière"), ('view_attendance_analytics', "Peut consulter l'analyse d'assiduité"), ('view_discipline_analytics', "Peut consulter l'analyse disciplinaire"), ('view_class_analytics', "Peut consulter l'analyse des classes"), ('view_student_summary', 'Peut consulter les synthèses élèves en BI'), ('compare_academic_years', 'Peut comparer plusieurs années scolaires'), ('export_bi_reports', 'Peut exporter les rapports BI')], 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
    ]
