# Generated by Django 5.2.16 on 2026-07-28 13:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secretariat', '0004_school_class_letter_and_unique_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Code')),
                ('name', models.CharField(db_index=True, max_length=140, verbose_name='Nom')),
                ('observation_type', models.CharField(choices=[('POSITIVE', 'Positive'), ('NEGATIVE', 'Négative'), ('NEUTRE', 'Neutre')], db_index=True, default='NEGATIVE', max_length=10, verbose_name="Type d'observation")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('default_severity', models.CharField(choices=[('FAIBLE', 'Faible'), ('MODERE', 'Modéré'), ('GRAVE', 'Grave'), ('TRES_GRAVE', 'Très grave')], db_index=True, default='MODERE', max_length=12, verbose_name='Gravité par défaut')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_archived', models.BooleanField(db_index=True, default=False, verbose_name='Archivée')),
            ],
            options={
                'verbose_name': 'Catégorie de conduite',
                'verbose_name_plural': 'Catégories de conduite',
                'ordering': ['observation_type', 'name'],
                'indexes': [models.Index(fields=['observation_type', 'is_active'], name='discipline__observa_3c21b6_idx'), models.Index(fields=['default_severity', 'is_active'], name='discipline__default_772127_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceScanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('event_type', models.CharField(choices=[('ARRIVEE', 'Arrivée'), ('SORTIE', 'Sortie')], db_index=True, max_length=10, verbose_name="Type d'événement")),
                ('result', models.CharField(choices=[('SUCCES', 'Succès'), ('DOUBLE', 'Doublon'), ('CARTE_BLOQUEE', 'Carte bloquée'), ('QR_INCONNU', 'QR inconnu'), ('ANNEE_INVALIDE', 'Année invalide'), ('INSCRIPTION_INACTIVE', 'Inscription inactive'), ('ERREUR', 'Erreur')], db_index=True, max_length=22, verbose_name='Résultat')),
                ('scanned_at', models.DateTimeField(db_index=True, verbose_name='Scanné le')),
                ('qr_identifier', models.CharField(blank=True, max_length=255, verbose_name='Identifiant QR')),
                ('message', models.CharField(blank=True, max_length=255, verbose_name='Message')),
                ('scanner_device', models.CharField(blank=True, max_length=120, verbose_name='Appareil')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_scan_events', to='secretariat.academicyear', verbose_name='Année scolaire')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_scan_events', to='secretariat.enrollment', verbose_name='Inscription')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_scan_events', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_scan_events', to='secretariat.student', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Événement de scan',
                'verbose_name_plural': 'Événements de scan',
                'ordering': ['-scanned_at', '-created_at'],
                'indexes': [models.Index(fields=['academic_year', 'scanned_at'], name='discipline__academi_26ded9_idx'), models.Index(fields=['enrollment', 'scanned_at'], name='discipline__enrollm_166360_idx'), models.Index(fields=['result', 'scanned_at'], name='discipline__result_f7f408_idx'), models.Index(fields=['event_type', 'scanned_at'], name='discipline__event_t_1587bc_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('label', models.CharField(max_length=120, verbose_name='Libellé')),
                ('start_time', models.TimeField(verbose_name="Heure d'entrée")),
                ('tolerance_minutes', models.PositiveSmallIntegerField(default=0, verbose_name='Tolérance (minutes)')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Heure de sortie')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_archived', models.BooleanField(db_index=True, default=False, verbose_name='Archivée')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_schedules', to='secretariat.academicyear', verbose_name='Année scolaire')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_schedules', to='secretariat.schoollevel', verbose_name='Niveau')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_schedules', to='secretariat.schoolclass', verbose_name='Classe')),
            ],
            options={
                'verbose_name': 'Horaire de pointage',
                'verbose_name_plural': 'Horaires de pointage',
                'ordering': ['academic_year', 'school_class__name', 'level__order', 'label'],
                'indexes': [models.Index(fields=['academic_year', 'is_active'], name='discipline__academi_bf5a37_idx'), models.Index(fields=['school_class', 'is_active'], name='discipline__school__5e17cf_idx'), models.Index(fields=['level', 'is_active'], name='discipline__level_i_001519_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('tolerance_minutes__gte', 0)), name='discipline_schedule_tolerance_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('status', models.CharField(choices=[('PRESENT', 'Présent'), ('RETARD', 'Retard'), ('ABSENT', 'Absent'), ('ABSENCE_JUSTIFIEE', 'Absence justifiée'), ('MALADE', 'Malade'), ('DISPENSE', 'Dispensé'), ('SORTIE_AUTORISEE', 'Sortie autorisée'), ('RENVOYE_TEMP', 'Renvoyé temporairement')], db_index=True, default='PRESENT', max_length=20, verbose_name='Statut')),
                ('arrival_time', models.TimeField(blank=True, null=True, verbose_name="Heure d'arrivée")),
                ('exit_time', models.TimeField(blank=True, null=True, verbose_name='Heure de sortie')),
                ('late_minutes', models.PositiveIntegerField(default=0, verbose_name='Minutes de retard')),
                ('source', models.CharField(choices=[('QR', 'QR'), ('MANUEL', 'Manuel'), ('IMPORT', 'Import')], default='MANUEL', max_length=12, verbose_name='Source du pointage')),
                ('modification_reason', models.TextField(blank=True, verbose_name='Motif de modification')),
                ('note', models.TextField(blank=True, verbose_name='Observation')),
                ('is_day_closed', models.BooleanField(db_index=True, default=False, verbose_name='Journée clôturée')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_attendances', to='secretariat.academicyear', verbose_name='Année scolaire')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_attendances', to='secretariat.enrollment', verbose_name='Inscription')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_attendances', to='secretariat.student', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Présence journalière',
                'verbose_name_plural': 'Présences journalières',
                'ordering': ['-date', 'enrollment__school_class__name', 'student__nom', 'student__prenom'],
                'indexes': [models.Index(fields=['academic_year', 'date'], name='discipline__academi_fb8e67_idx'), models.Index(fields=['status', 'date'], name='discipline__status_ab48a6_idx'), models.Index(fields=['enrollment', 'date'], name='discipline__enrollm_e607bf_idx'), models.Index(fields=['student', 'date'], name='discipline__student_84a4a6_idx')],
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'date'), name='discipline_unique_attendance_per_enrollment_day'), models.CheckConstraint(condition=models.Q(('late_minutes__gte', 0)), name='discipline_attendance_late_non_negative')],
            },
        ),
    ]
