# Generated by Codex on 2026-07-30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("secretariat", "0004_school_class_letter_and_unique_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("discipline", "0002_discipline_workflows"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassAttendanceSheet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Créé le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Modifié le")),
                ("date", models.DateField(db_index=True, verbose_name="Date")),
                ("status", models.CharField(choices=[("NON_SAISIE", "Non saisie"), ("BROUILLON", "Brouillon"), ("VALIDEE", "Validée"), ("CLOTUREE", "Clôturée")], db_index=True, default="NON_SAISIE", max_length=12, verbose_name="Statut")),
                ("total_students", models.PositiveIntegerField(default=0)),
                ("total_present", models.PositiveIntegerField(default=0)),
                ("total_absent", models.PositiveIntegerField(default=0)),
                ("total_unmarked", models.PositiveIntegerField(default=0)),
                ("validation_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("modification_reason", models.TextField(blank=True)),
                ("academic_year", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="attendance_sheets", to="secretariat.academicyear", verbose_name="Année scolaire")),
                ("closed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="closed_attendance_sheets", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_attendance_sheets", to=settings.AUTH_USER_MODEL)),
                ("school_class", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="attendance_sheets", to="secretariat.schoolclass", verbose_name="Classe")),
                ("validated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="validated_attendance_sheets", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-date", "school_class__name"],
                "constraints": [
                    models.UniqueConstraint(fields=("school_class", "date"), name="discipline_unique_class_sheet_per_day")
                ],
                "indexes": [
                    models.Index(fields=["academic_year", "date"], name="disc_sheet_year_date_idx"),
                    models.Index(fields=["school_class", "date"], name="disc_sheet_class_date_idx"),
                    models.Index(fields=["status", "date"], name="disc_sheet_status_date_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="StudentAttendanceRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Créé le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Modifié le")),
                ("status", models.CharField(choices=[("NON_MARQUE", "Non marqué"), ("PRESENT", "Présent"), ("ABSENT", "Absent")], db_index=True, default="NON_MARQUE", max_length=12)),
                ("presence_value", models.SmallIntegerField(blank=True, null=True)),
                ("mention", models.CharField(blank=True, max_length=6)),
                ("observation", models.TextField(blank=True)),
                ("enrollment", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="sheet_attendance_records", to="secretariat.enrollment")),
                ("recorded_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="recorded_sheet_attendance_records", to=settings.AUTH_USER_MODEL)),
                ("school_class", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="sheet_attendance_records", to="secretariat.schoolclass")),
                ("sheet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="records", to="discipline.classattendancesheet")),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="sheet_attendance_records", to="secretariat.student")),
            ],
            options={
                "ordering": ["student__nom", "student__prenom"],
                "constraints": [
                    models.UniqueConstraint(fields=("sheet", "enrollment"), name="discipline_unique_sheet_record_per_enrollment"),
                    models.CheckConstraint(condition=models.Q(("presence_value__in", [0, 1]), ("presence_value__isnull", True), _connector="OR"), name="discipline_record_presence_value_allowed"),
                    models.CheckConstraint(condition=(models.Q(("status", "NON_MARQUE"), ("presence_value__isnull", True), ("mention", "")) | models.Q(("status", "PRESENT"), ("presence_value", 1), ("mention", "OK")) | models.Q(("status", "ABSENT"), ("presence_value", 0), ("mention", "ABS"))), name="discipline_record_status_value_mention_consistent"),
                ],
                "indexes": [
                    models.Index(fields=["sheet", "status"], name="disc_record_sheet_status_idx"),
                    models.Index(fields=["enrollment", "status"], name="disc_record_enroll_status_idx"),
                    models.Index(fields=["student", "status"], name="disc_record_student_status_idx"),
                    models.Index(fields=["school_class", "status"], name="disc_record_class_status_idx"),
                ],
            },
        ),
    ]
